spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome self-taught PROD"
  contactDetails:
    name: "John Owner"
    email: "John@mail.es"
  onCallSupport:
    -(456) 555-754
    -(456) 555-756